<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="editoroperation" nsURI="http://hyvar-project.eu/evolution/editoroperation/1.0"
    nsPrefix="editoroperation">
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evoStep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeature" abstract="true"
      eSuperTypes="#//DwEditorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureCreate" eSuperTypes="#//DwEditorOperationFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureDelete" eSuperTypes="#//DwEditorOperationFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureRename" eSuperTypes="#//DwEditorOperationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureType" eSuperTypes="#//DwEditorOperationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldType" eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newType" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureGroup" eSuperTypes="#//DwEditorOperationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldGroup" eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newGroup" eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureVersion" abstract="true"
      eSuperTypes="#//DwEditorOperationFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyVersion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureVersionCreate"
      eSuperTypes="#//DwEditorOperationFeatureVersion"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureVersionDelete"
      eSuperTypes="#//DwEditorOperationFeatureVersion"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationFeatureVersionRename"
      eSuperTypes="#//DwEditorOperationFeatureVersion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationGroupType" eSuperTypes="#//DwEditorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldType" eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyGroupType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newType" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyGroupType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationAttribute" abstract="true"
      eSuperTypes="#//DwEditorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationAttributeCreate" eSuperTypes="#//DwEditorOperationAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationAttributeDelete" eSuperTypes="#//DwEditorOperationAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationAttributeRename" eSuperTypes="#//DwEditorOperationAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationAttributeMinMax" eSuperTypes="#//DwEditorOperationAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldMinMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newMinMax" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DwEditorOperationMinMax"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationAttributeEnum" eSuperTypes="#//DwEditorOperationAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldEnum" eType="ecore:EClass ../../eu.hyvar.feature.data/model/DataValues.ecore#//HyEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newEnum" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature.data/model/DataValues.ecore#//HyEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DwEditorOperationMinMax">
    <eLiterals name="MIN"/>
    <eLiterals name="MAX" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnum" abstract="true"
      eSuperTypes="#//DwEditorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enum" lowerBound="1" eType="ecore:EClass ../../eu.hyvar.feature.data/model/DataValues.ecore#//HyEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnumCreate" eSuperTypes="#//DwEditorOperationEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnumDelete" eSuperTypes="#//DwEditorOperationEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnumRename" eSuperTypes="#//DwEditorOperationEnum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnumLiteral" abstract="true"
      eSuperTypes="#//DwEditorOperationEnum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass ../../eu.hyvar.feature.data/model/DataValues.ecore#//HyEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnumLiteralCreate"
      eSuperTypes="#//DwEditorOperationEnumLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnumLiteralDelete"
      eSuperTypes="#//DwEditorOperationEnumLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationEnumLiteralRename"
      eSuperTypes="#//DwEditorOperationEnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.evolution/model/Evolution.ecore#//HyName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationConstraint" abstract="true"
      eSuperTypes="#//DwEditorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature.constraint/model/Constraint.ecore#//HyConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationConstraintCreate" eSuperTypes="#//DwEditorOperationConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationConstraintDelete" eSuperTypes="#//DwEditorOperationConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationContext" abstract="true"
      eSuperTypes="#//DwEditorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.context.information/model/ContextInformation.ecore#//HyContextualInformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationContextCreate" eSuperTypes="#//DwEditorOperationContext"/>
  <eClassifiers xsi:type="ecore:EClass" name="DwEditorOperationContextDelete" eSuperTypes="#//DwEditorOperationContext"/>
</ecore:EPackage>
