/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.validation;

import de.darwinspl.validation.AbstractExpressionDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ExpressionDslValidator extends AbstractExpressionDslValidator {
}
