/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.ui;

import de.darwinspl.ui.AbstractExpressionDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ExpressionDslUiModule extends AbstractExpressionDslUiModule {
  public ExpressionDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
