<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="temporalConstraint" nsURI="http://darwinspl.de/constraint/temporalconstraint/1.0"
    nsPrefix="temporalConstraint">
  <eClassifiers xsi:type="ecore:EClass" name="TemporalConstraint" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validSince" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validUntil" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalCardinalityConstraint" eSuperTypes="#//TemporalConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalReferenceConstraint" eSuperTypes="#//TemporalConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintType" eType="#//ConstraintTypeEnum"
        defaultValueLiteral="greaterThan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintTypeEnum">
    <eLiterals name="greaterThan" literal="greaterThan"/>
    <eLiterals name="lessThan" value="1" literal="lessThan"/>
    <eLiterals name="equals" value="2" literal="equals"/>
  </eClassifiers>
</ecore:EPackage>
