/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.darwinspl.ExpressionDslRuntimeModule;
import de.darwinspl.ExpressionDslStandaloneSetup;
import de.darwinspl.ide.ExpressionDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ExpressionDslIdeSetup extends ExpressionDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    ExpressionDslRuntimeModule _expressionDslRuntimeModule = new ExpressionDslRuntimeModule();
    ExpressionDslIdeModule _expressionDslIdeModule = new ExpressionDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_expressionDslRuntimeModule, _expressionDslIdeModule));
  }
}
