<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="constraint" nsURI="http://hyvar-project.eu/feature/constraint/1.0"
    nsPrefix="constraint">
  <eClassifiers xsi:type="ecore:EClass" name="HyConstraint" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootExpression" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HyConstraintModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//HyConstraint" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
