/*
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConstraintDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/darwinspl/constraint/dsl/parser/antlr/internal/InternalConstraintDsl.tokens");
	}
}
