<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stage" nsURI="https://darwinspl.de/stage/1.0" nsPrefix="stage">
  <eClassifiers xsi:type="ecore:EClass" name="StageModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureModel" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stages" lowerBound="1"
        upperBound="-1" eType="#//Stage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Role" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyTemporalElement ../../eu.hyvar.evolution/model/Evolution.ecore#//HyNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasAssigned" lowerBound="1"
        upperBound="-1" eType="#//Role" eOpposite="#//Role/assignedTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composition" upperBound="-1"
        eType="#//StageComposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyTemporalElement ../../eu.hyvar.evolution/model/Evolution.ecore#//HyNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" upperBound="-1"
        eType="#//Stage" eOpposite="#//Stage/hasAssigned"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inclusions" upperBound="-1"
        eType="#//RoleInclusion" containment="true" eOpposite="#//RoleInclusion/inclusionsFor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedBy" upperBound="-1"
        eType="#//RoleInclusion" eOpposite="#//RoleInclusion/includes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleInclusion" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyLinearTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/includedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inclusionsFor" eType="#//Role"
        eOpposite="#//Role/inclusions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StageComposition" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyLinearTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyGroup"/>
  </eClassifiers>
</ecore:EPackage>
