<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stage" nsURI="https://darwinspl.de/stage/1.0" nsPrefix="stage">
  <eClassifiers xsi:type="ecore:EClass" name="StageModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureModel" lowerBound="1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stageOrder" lowerBound="1"
        upperBound="-1" eType="#//StageOrder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleHierarchy" lowerBound="1"
        upperBound="-1" eType="#//RoleHierarchy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StageOrder" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyLinearTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stages" upperBound="-1"
        eType="#//Stage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleHierarchy" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyLinearTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" upperBound="-1"
        eType="#//Stage" eOpposite="#//Stage/hasAssigned"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasAssigned" lowerBound="1"
        upperBound="-1" eType="#//Role" eOpposite="#//Role/assignedTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composition" lowerBound="1"
        upperBound="-1" eType="#//StageComposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StageComposition" eSuperTypes="../../eu.hyvar.evolution/model/Evolution.ecore#//HyLinearTemporalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="ecore:EClass ../../eu.hyvar.feature/model/Feature.ecore#//HyGroup"/>
  </eClassifiers>
</ecore:EPackage>
