/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.ui.quickfix;

import de.darwinspl.ui.quickfix.ExpressionDslQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ConstraintDslQuickfixProvider extends ExpressionDslQuickfixProvider {
}
