/*
 * generated by Xtext 2.12.0
 */
package de.darwinspl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExpressionDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/darwinspl/parser/antlr/internal/InternalExpressionDsl.tokens");
	}
}
