/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.scoping;

import de.darwinspl.constraint.dsl.scoping.AbstractConstraintDslScopeProvider;
import de.darwinspl.scoping.ExpressionDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ConstraintDslScopeProvider extends AbstractConstraintDslScopeProvider {
  public ConstraintDslScopeProvider() {
    super();
    ExpressionDslScopeProvider expressionScope = new ExpressionDslScopeProvider();
    this.setDelegate(expressionScope);
  }
}
