/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.ide;

import de.darwinspl.constraint.dsl.ide.AbstractConstraintDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ConstraintDslIdeModule extends AbstractConstraintDslIdeModule {
}
