/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.darwinspl.constraint.dsl.ConstraintDslRuntimeModule;
import de.darwinspl.constraint.dsl.ConstraintDslStandaloneSetup;
import de.darwinspl.constraint.dsl.ide.ConstraintDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ConstraintDslIdeSetup extends ConstraintDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    ConstraintDslRuntimeModule _constraintDslRuntimeModule = new ConstraintDslRuntimeModule();
    ConstraintDslIdeModule _constraintDslIdeModule = new ConstraintDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_constraintDslRuntimeModule, _constraintDslIdeModule));
  }
}
