/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.ui;

import de.darwinspl.constraint.dsl.ui.AbstractConstraintDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ConstraintDslUiModule extends AbstractConstraintDslUiModule {
  public ConstraintDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
