/*
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.scoping;

import de.darwinspl.scoping.ExpressionDslScopeProvider;

public abstract class AbstractConstraintDslScopeProvider extends ExpressionDslScopeProvider {
}
