/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl;

import de.darwinspl.constraint.dsl.AbstractConstraintDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ConstraintDslRuntimeModule extends AbstractConstraintDslRuntimeModule {
}
