/*
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.ide


/**
 * Use this class to register ide components.
 */
class ConstraintDslIdeModule extends AbstractConstraintDslIdeModule {
}
