/**
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ConstraintDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
