/*
 * generated by Xtext 2.12.0
 */
package de.darwinspl.constraint.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ConstraintDslStandaloneSetup extends ConstraintDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ConstraintDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
